/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    BackImage: typeof import('./src/components/Back-Image.vue')['default']
    IconInfo: typeof import('./src/components/IconInfo.vue')['default']
    LinkInfo: typeof import('./src/components/LinkInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    TextInfo: typeof import('./src/components/TextInfo.vue')['default']
    Title: typeof import('./src/components/Title.vue')['default']
  }
}
